Adds "anchor" option
simeydotme/donutty pull request #39
Opened 2022-10-16 15:50 UTC by tobie

This option allows starting the donut from the top or the bottom. Defaults to bottom.

2022-10-17 17:35 UTC, simeydotme requested changes
I've marked two things to change syntactically to align with the formatting!
Other than those, great PR!

P.S. Have you tested this with both a `circle` and non-`circle` donut chart? looks like it should just invert the bitten donut into kind of a horse-shoe? But I can double-check after the PR is ready!

2022-10-17 17:35 UTC, simeydotme commented on src/donutty.js
> +        this.options.anchor =      (isDefined( this.options.anchor ) && this.options.anchor == "top") ? "top" : "bottom";
Nice PR!
I only ask if we can make these small tweaks so it matches the formatting and strict `===`

```suggestion
        this.options.anchor =      isDefined( this.options.anchor ) && this.options.anchor === "top" ? "top" : "bottom";
```

2022-10-17 17:35 UTC, simeydotme commented on src/donutty.js
> +            rotateAnchor = this.options.anchor == "top" ? 180 : 0,
```suggestion
            rotateAnchor = this.options.anchor === "top" ? 180 : 0,
```

2022-10-17 22:24 UTC, tobie commented
> P.S. Have you tested this with both a circle and non-circle donut chart? looks like it should just invert the bitten donut into kind of a horse-shoe? But I can double-check after the PR is ready!

Yes, I have. It looks like an upside down gauge. Maybe that's weird? If so, we could make it for the full circle version only.

2022-10-18 01:15 UTC, simeydotme commented
> > P.S. Have you tested this with both a circle and non-circle donut chart? looks like it should just invert the bitten donut into kind of a horse-shoe? But I can double-check after the PR is ready!
> 
> Yes, I have. It looks like an upside down gauge. Maybe that's weird? If so, we could make it for the full circle version only.

Oh cool, no no, not bothered if it's a little strange, the implementer can decide that. Just wanted to confirm its not doing anything unexpected (like sideways) :)

2022-10-18 07:09 UTC, tobie commented
Hey, I’m not sure if there’s anything else you want me to do, here. I’m also confused about the labels you added to the pull request as “good first issue” and “help needed” labels are generally applied to issues before anyone steps up to offer a solution, not to pull requests or issues opened in order to discuss a feature prior to writing a PR for it.

2022-10-18 07:09 UTC, tobie commented
> Just wanted to confirm its not doing anything unexpected (like sideways) :)

It is not!

2022-10-18 16:15 UTC, merged

2022-10-18 16:20 UTC, simeydotme commented
Hi @tobie !
Thanks for this, it's been updated to `2.4.0` now with the new changes.

One thing; I had to revert the 180d rotation you added in favour of the scaling I mentioned before. This is because of the half-donut, specifically when "RTL" text mode was on. The rotation was negating the direction of the donut. Not a show-stopper, but it was weird.

Here's a little screencapture of the correctly functioning version (2.4.0) with scale instead of rotate! :)

![donutty-tests](https://user-images.githubusercontent.com/2817396/196486996-c80b61ed-d74f-49c7-8439-945681dda986.gif)

2022-10-18 16:25 UTC, simeydotme reviewed
👍

2022-10-19 10:09 UTC, tobie commented
Thanks a lot!